# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FigmaKit < Formula
  desc "CLI for programmatic Figma design via the MCP server"
  homepage "https://github.com/dop-amine/figma-kit"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_darwin_amd64.tar.gz"
      sha256 "8d310265d422083ec9672c04b2a7d72d8d82bf67a4ba0d935398ed5c8669bbd2"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_darwin_arm64.tar.gz"
      sha256 "27693e6b9cd32c3e42d300a0e58bb3d02c4ac87cbfc7fef97cc52a4f6eaf6d75"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_linux_amd64.tar.gz"
      sha256 "cd7dc6804d58c6a2424672a283a3ec40f1f943dbe73b43d663cb8c16d2a98136"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_linux_arm64.tar.gz"
      sha256 "1b5a5f7f9a8e44354a0271ffdff5a547104ee1044df1507c7bcd689d8f4b9aeb"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end
end
