# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FigmaKit < Formula
  desc "CLI for programmatic Figma design via the MCP server"
  homepage "https://github.com/dop-amine/figma-kit"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_darwin_amd64.tar.gz"
      sha256 "982adb9f74741b99d98070440aebdc637c06bda01311165245d4930d22d66bc8"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_darwin_arm64.tar.gz"
      sha256 "8aaa546658088eddf4f733944336e57edcebaf309c21c4ba51400408742fabaa"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_linux_amd64.tar.gz"
      sha256 "ae062b343854f7b20979f9f684945c42b7b5645e96405d64d9457c7a4753c50f"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.4.0/figma-kit_0.4.0_linux_arm64.tar.gz"
      sha256 "dd0524c933564ff2d3fad9ecac53ab023ff8b0243d79b1e438853f146f2417f5"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end
end
