# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FigmaKit < Formula
  desc "CLI for programmatic Figma design via the MCP server"
  homepage "https://github.com/dop-amine/figma-kit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.3.0/figma-kit_0.3.0_darwin_amd64.tar.gz"
      sha256 "a49d962ad6ae1107a8b9e88b692f388c222b1babb5a29894ce8cc983b63a322a"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.3.0/figma-kit_0.3.0_darwin_arm64.tar.gz"
      sha256 "511dc69432ce23aef92a9e1ee0d60f9e11e0c74a2834d97d78a0f0e6ee5cfd3f"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.3.0/figma-kit_0.3.0_linux_amd64.tar.gz"
      sha256 "8a5749d7c55155f57ee97c2b2072a669d7fed3216863e9d29d80b5734a35379b"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v0.3.0/figma-kit_0.3.0_linux_arm64.tar.gz"
      sha256 "c419cc55dcd83aafc4261e90c09661b7847411740f3481cb3dc8fba54b682a39"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end
end
