# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FigmaKit < Formula
  desc "CLI for programmatic Figma design via the MCP server"
  homepage "https://github.com/dop-amine/figma-kit"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.1/figma-kit_1.0.1_darwin_amd64.tar.gz"
      sha256 "6673629747220372998cef42d867cbd7f1375a2a7271518b1c1a600c4a26ef4b"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.1/figma-kit_1.0.1_darwin_arm64.tar.gz"
      sha256 "42b0dfdedd664b56523ac84ae2f243afaa6bffec6a6b36ff24f2c47769805cdf"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.1/figma-kit_1.0.1_linux_amd64.tar.gz"
      sha256 "33fb78d09a534be846af62f22999a4f01f43c579ccc18f06321ea376808c75b6"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.1/figma-kit_1.0.1_linux_arm64.tar.gz"
      sha256 "4709a612dd57a7915f6dc73b7776f7ebebc36a4f7b2c31193e7547a3cbdbf0b5"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end
end
