# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FigmaKit < Formula
  desc "CLI for programmatic Figma design via the MCP server"
  homepage "https://github.com/dop-amine/figma-kit"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.0/figma-kit_1.0.0_darwin_amd64.tar.gz"
      sha256 "1b4a42e9b7ec151e843d9260cecdc2e5de70f67c24f31f7b364948e3a65f6187"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.0/figma-kit_1.0.0_darwin_arm64.tar.gz"
      sha256 "f85027c427bfca9cd5a163343fa724b6cb858bd0351e722913f82436c6d67de9"

      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.0/figma-kit_1.0.0_linux_amd64.tar.gz"
      sha256 "a6e7099326491589f8811ffa5a119d4da97eacb08142db0b762998e4aecbf776"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dop-amine/figma-kit/releases/download/v1.0.0/figma-kit_1.0.0_linux_arm64.tar.gz"
      sha256 "69606f61cfa8a28563be1c8aaf870f75cba08e7bad68d5914aa74807dd20062e"
      define_method(:install) do
        bin.install "figma-kit"
      end
    end
  end
end
